# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('app_specification', models.CharField(max_length=200)),
                ('app_requirements', models.CharField(max_length=250)),
                ('cover_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='pro_pic',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwares',
            name='own_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Users'),
        ),
    ]
