# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0002_auto_20170331_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwares',
            name='cover_pic',
            field=models.FileField(default='default_app_icon-vflohrH6B.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='pro_pic',
            field=models.FileField(default='default.jpg', upload_to=''),
        ),
    ]
