# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0003_auto_20170331_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softwares11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=30)),
                ('app_specification', models.CharField(max_length=200)),
                ('app_requirements', models.CharField(max_length=250)),
                ('cover_pic', models.FileField(default='default_app_icon-vflohrH6B.png', upload_to='')),
                ('own_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Users')),
            ],
        ),
    ]
