# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0004_softwares11'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwares11',
            name='own_by',
        ),
        migrations.RenameField(
            model_name='softwares',
            old_name='app_requirements',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='app_name',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='app_specification',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='cover_pic',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pro_pic',
        ),
        migrations.AddField(
            model_name='softwares',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwares',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softwares',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='softwares',
            name='specification',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Softwares11',
        ),
    ]
