# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0006_auto_20170501_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwares',
            name='zip_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
