# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0007_softwares_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='softwares',
            old_name='downloads',
            new_name='download',
        ),
        migrations.AddField(
            model_name='downloads',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Softwares'),
        ),
        migrations.AddField(
            model_name='downloads',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Users'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='soft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Softwares'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='General.Users'),
        ),
    ]
