# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('General', '0008_auto_20170502_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwares',
            name='cover_pic',
            field=models.FileField(blank=True, default='software-icon-30.png', upload_to=''),
        ),
    ]
